# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"\"\n\x0fServeClientArgs\x12\x0f\n\x07request\x18\x01 \x01(\t\"C\n\x10ServeClientReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x10\n\x08leaderID\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\"\xaa\x01\n\x0f\x41ppendEntryArgs\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x10\n\x08leaderId\x18\x02 \x01(\t\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x04\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x04\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x04\x12\x15\n\rleaseDuration\x18\x07 \x01(\x04\"1\n\x10\x41ppendEntryReply\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\"_\n\x0fRequestVoteArgs\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\t\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x04\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x04\"L\n\x10RequestVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\x12\x15\n\rleaseDuration\x18\x03 \x01(\x04\")\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t2\xcd\x01\n\x0bRaftService\x12>\n\x0bServeClient\x12\x15.raft.ServeClientArgs\x1a\x16.raft.ServeClientReply\"\x00\x12>\n\x0b\x41ppendEntry\x12\x15.raft.AppendEntryArgs\x1a\x16.raft.AppendEntryReply\"\x00\x12>\n\x0bRequestVote\x12\x15.raft.RequestVoteArgs\x1a\x16.raft.RequestVoteReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVECLIENTARGS']._serialized_start=20
  _globals['_SERVECLIENTARGS']._serialized_end=54
  _globals['_SERVECLIENTREPLY']._serialized_start=56
  _globals['_SERVECLIENTREPLY']._serialized_end=123
  _globals['_APPENDENTRYARGS']._serialized_start=126
  _globals['_APPENDENTRYARGS']._serialized_end=296
  _globals['_APPENDENTRYREPLY']._serialized_start=298
  _globals['_APPENDENTRYREPLY']._serialized_end=347
  _globals['_REQUESTVOTEARGS']._serialized_start=349
  _globals['_REQUESTVOTEARGS']._serialized_end=444
  _globals['_REQUESTVOTEREPLY']._serialized_start=446
  _globals['_REQUESTVOTEREPLY']._serialized_end=522
  _globals['_LOGENTRY']._serialized_start=524
  _globals['_LOGENTRY']._serialized_end=565
  _globals['_RAFTSERVICE']._serialized_start=568
  _globals['_RAFTSERVICE']._serialized_end=773
# @@protoc_insertion_point(module_scope)
